#!/usr/bin/env bash
# gen-gui-video.sh — Build the GUI demo video from SVG mockups + narration.
#
# Approach: screenshot slideshow + espeak-ng narration
#   • 4 PNG frames generated from SVG mockups (no Qt/GL required)
#   • Timed to match voiceover.txt section boundaries
#   • Narration from voice/narration.wav (pre-generated by gen-voice.sh)
#   • Final output: gui-demo.mp4
#
# Usage:
#   bash demo/gen-gui-video.sh          # from repo root
#   bash gen-gui-video.sh               # from demo/ directory
#
# Dependencies: python3, rsvg-convert, ffmpeg, (optional) espeak-ng
set -e

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
SS_DIR="$SCRIPT_DIR/screenshots"
VOICE_DIR="$SCRIPT_DIR/voice"
TMP_DIR="$SCRIPT_DIR/.build-tmp"

mkdir -p "$SS_DIR" "$TMP_DIR"

echo "=== Step 1: Generate SVG mockups ==="
python3 "$SCRIPT_DIR/gen-gui-mockup.py"

echo ""
echo "=== Step 2: Convert SVGs → PNGs (1280×800) ==="
rsvg-convert -w 1280 -h 800 "$SCRIPT_DIR/gui-map.svg"       -o "$SS_DIR/map.png"
rsvg-convert -w 1280 -h 800 "$SCRIPT_DIR/gui-upload.svg"    -o "$SS_DIR/upload.png"
rsvg-convert -w 1280 -h 800 "$SCRIPT_DIR/gui-downloads.svg" -o "$SS_DIR/downloads.png"
rsvg-convert -w 1280 -h 800 "$SCRIPT_DIR/gui-settings.svg"  -o "$SS_DIR/settings.png"
echo "  map.png upload.png downloads.png settings.png"

echo ""
echo "=== Step 3: Regenerate narration audio ==="
if [ ! -f "$VOICE_DIR/narration.wav" ]; then
    echo "  narration.wav missing — running gen-voice.sh"
    bash "$SCRIPT_DIR/gen-voice.sh"
else
    echo "  narration.wav already exists ($(du -h "$VOICE_DIR/narration.wav" | cut -f1))"
fi

# Get actual audio duration
AUDIO_DUR=$(ffprobe -v quiet -show_entries format=duration \
    -of csv=p=0 "$VOICE_DIR/narration.wav" 2>/dev/null || echo "145")
AUDIO_DUR_INT=$(printf "%.0f" "$AUDIO_DUR")
echo "  Audio duration: ${AUDIO_DUR}s"

echo ""
echo "=== Step 4: Build video segments ==="
# Segment timing (seconds) based on voiceover.txt section boundaries:
#   Map intro + tour:   0:00 – 0:36   (36s)  lines 01-07
#   Upload tab:         0:36 – 1:27   (51s)  lines 08-16
#   Downloads tab:      1:27 – 1:39   (12s)  lines 17-18
#   Settings tab:       1:39 – 1:57   (18s)  lines 19-21
#   Map closing:        1:57 – end    (28s)  lines 22-24
#   Total ≈ 145s — matches narration.wav duration

SEG_DURS=(36 51 12 18 28)
SEG_IMGS=(
    "$SS_DIR/map.png"
    "$SS_DIR/upload.png"
    "$SS_DIR/downloads.png"
    "$SS_DIR/settings.png"
    "$SS_DIR/map.png"
)
SEG_NAMES=(map upload downloads settings map-close)

CONCAT_LIST="$TMP_DIR/concat.txt"
> "$CONCAT_LIST"

for i in "${!SEG_DURS[@]}"; do
    dur="${SEG_DURS[$i]}"
    img="${SEG_IMGS[$i]}"
    name="${SEG_NAMES[$i]}"
    seg_out="$TMP_DIR/seg-${name}.mp4"

    echo "  segment $((i+1))/5: ${name} (${dur}s)"
    ffmpeg -y -loglevel error \
        -loop 1 -i "$img" \
        -t "$dur" \
        -vf "scale=1280:800,format=yuv420p" \
        -r 25 \
        -c:v libx264 -preset fast -crf 22 \
        "$seg_out"

    echo "file '$seg_out'" >> "$CONCAT_LIST"
done

echo ""
echo "=== Step 5: Concat segments ==="
SILENT_VIDEO="$TMP_DIR/video-silent.mp4"
ffmpeg -y -loglevel error \
    -f concat -safe 0 -i "$CONCAT_LIST" \
    -c copy \
    "$SILENT_VIDEO"

echo ""
echo "=== Step 6: Mux video + narration → gui-demo.mp4 ==="
OUT="$SCRIPT_DIR/gui-demo.mp4"
# Trim/pad audio to exact video duration to ensure sync
ffmpeg -y -loglevel error \
    -i "$SILENT_VIDEO" \
    -i "$VOICE_DIR/narration.wav" \
    -c:v copy \
    -c:a aac -b:a 128k \
    -shortest \
    "$OUT"

echo ""
echo "=== Done ==="
ls -lh "$OUT"
VIDEO_DUR=$(ffprobe -v quiet -show_entries format=duration \
    -of csv=p=0 "$OUT" 2>/dev/null || echo "?")
echo "  Duration: ${VIDEO_DUR}s"
echo "  Output:   $OUT"
echo ""
echo "  Frames:"
echo "    00:00–00:36  Map tab     — geo pins, timeline slider"
echo "    00:36–01:27  Upload tab  — queue, progress bars, dedup"
echo "    01:27–01:39  Downloads   — storage bar, owned videos"
echo "    01:39–01:57  Settings    — storage, monitoring, node status"
echo "    01:57–end    Map tab     — closing stack context"

# Cleanup temp files
rm -rf "$TMP_DIR"
